package scripting.wrapper.world;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;

import net.minecraft.block.Block;
import net.minecraft.item.Item;

/**
 * See {@link net.minecraft.item.Item}.
 * Fields generated by {@link ScriptItemID#printAll()}
 *
 */
public class ScriptItemID {
	
	/**
	 * Method used to generate the fields.
	 */
	private static void printAll() {
		for (Field f : Item.class.getDeclaredFields()) {
			f.setAccessible(true);
			if (Modifier.isStatic(f.getModifiers()) && Item.class.isAssignableFrom(f.getType())) {
				String name = f.getName();
				System.out.println("public static final int " + name + " = Item." + name + ".itemID;");
			}
		}
	}
	
	public static boolean isValid(int id) {
		return id >= 0 && id < Item.itemsList.length && Item.itemsList[id] != null;
	}
	
	public static final int shovelIron = Item.shovelIron.itemID;
	public static final int pickaxeIron = Item.pickaxeIron.itemID;
	public static final int axeIron = Item.axeIron.itemID;
	public static final int flintAndSteel = Item.flintAndSteel.itemID;
	public static final int appleRed = Item.appleRed.itemID;
	public static final int bow = Item.bow.itemID;
	public static final int arrow = Item.arrow.itemID;
	public static final int coal = Item.coal.itemID;
	public static final int diamond = Item.diamond.itemID;
	public static final int ingotIron = Item.ingotIron.itemID;
	public static final int ingotGold = Item.ingotGold.itemID;
	public static final int swordIron = Item.swordIron.itemID;
	public static final int swordWood = Item.swordWood.itemID;
	public static final int shovelWood = Item.shovelWood.itemID;
	public static final int pickaxeWood = Item.pickaxeWood.itemID;
	public static final int axeWood = Item.axeWood.itemID;
	public static final int swordStone = Item.swordStone.itemID;
	public static final int shovelStone = Item.shovelStone.itemID;
	public static final int pickaxeStone = Item.pickaxeStone.itemID;
	public static final int axeStone = Item.axeStone.itemID;
	public static final int swordDiamond = Item.swordDiamond.itemID;
	public static final int shovelDiamond = Item.shovelDiamond.itemID;
	public static final int pickaxeDiamond = Item.pickaxeDiamond.itemID;
	public static final int axeDiamond = Item.axeDiamond.itemID;
	public static final int stick = Item.stick.itemID;
	public static final int bowlEmpty = Item.bowlEmpty.itemID;
	public static final int bowlSoup = Item.bowlSoup.itemID;
	public static final int swordGold = Item.swordGold.itemID;
	public static final int shovelGold = Item.shovelGold.itemID;
	public static final int pickaxeGold = Item.pickaxeGold.itemID;
	public static final int axeGold = Item.axeGold.itemID;
	public static final int silk = Item.silk.itemID;
	public static final int feather = Item.feather.itemID;
	public static final int gunpowder = Item.gunpowder.itemID;
	public static final int hoeWood = Item.hoeWood.itemID;
	public static final int hoeStone = Item.hoeStone.itemID;
	public static final int hoeIron = Item.hoeIron.itemID;
	public static final int hoeDiamond = Item.hoeDiamond.itemID;
	public static final int hoeGold = Item.hoeGold.itemID;
	public static final int seeds = Item.seeds.itemID;
	public static final int wheat = Item.wheat.itemID;
	public static final int bread = Item.bread.itemID;
	public static final int helmetLeather = Item.helmetLeather.itemID;
	public static final int plateLeather = Item.plateLeather.itemID;
	public static final int legsLeather = Item.legsLeather.itemID;
	public static final int bootsLeather = Item.bootsLeather.itemID;
	public static final int helmetChain = Item.helmetChain.itemID;
	public static final int plateChain = Item.plateChain.itemID;
	public static final int legsChain = Item.legsChain.itemID;
	public static final int bootsChain = Item.bootsChain.itemID;
	public static final int helmetIron = Item.helmetIron.itemID;
	public static final int plateIron = Item.plateIron.itemID;
	public static final int legsIron = Item.legsIron.itemID;
	public static final int bootsIron = Item.bootsIron.itemID;
	public static final int helmetDiamond = Item.helmetDiamond.itemID;
	public static final int plateDiamond = Item.plateDiamond.itemID;
	public static final int legsDiamond = Item.legsDiamond.itemID;
	public static final int bootsDiamond = Item.bootsDiamond.itemID;
	public static final int helmetGold = Item.helmetGold.itemID;
	public static final int plateGold = Item.plateGold.itemID;
	public static final int legsGold = Item.legsGold.itemID;
	public static final int bootsGold = Item.bootsGold.itemID;
	public static final int flint = Item.flint.itemID;
	public static final int porkRaw = Item.porkRaw.itemID;
	public static final int porkCooked = Item.porkCooked.itemID;
	public static final int painting = Item.painting.itemID;
	public static final int appleGold = Item.appleGold.itemID;
	public static final int sign = Item.sign.itemID;
	public static final int doorWood = Item.doorWood.itemID;
	public static final int bucketEmpty = Item.bucketEmpty.itemID;
	public static final int bucketWater = Item.bucketWater.itemID;
	public static final int bucketLava = Item.bucketLava.itemID;
	public static final int minecartEmpty = Item.minecartEmpty.itemID;
	public static final int saddle = Item.saddle.itemID;
	public static final int doorIron = Item.doorIron.itemID;
	public static final int redstone = Item.redstone.itemID;
	public static final int snowball = Item.snowball.itemID;
	public static final int boat = Item.boat.itemID;
	public static final int leather = Item.leather.itemID;
	public static final int bucketMilk = Item.bucketMilk.itemID;
	public static final int brick = Item.brick.itemID;
	public static final int clay = Item.clay.itemID;
	public static final int reed = Item.reed.itemID;
	public static final int paper = Item.paper.itemID;
	public static final int book = Item.book.itemID;
	public static final int slimeBall = Item.slimeBall.itemID;
	public static final int minecartCrate = Item.minecartCrate.itemID;
	public static final int minecartPowered = Item.minecartPowered.itemID;
	public static final int egg = Item.egg.itemID;
	public static final int compass = Item.compass.itemID;
	public static final int fishingRod = Item.fishingRod.itemID;
	public static final int pocketSundial = Item.pocketSundial.itemID;
	public static final int glowstone = Item.glowstone.itemID;
	public static final int fishRaw = Item.fishRaw.itemID;
	public static final int fishCooked = Item.fishCooked.itemID;
	public static final int dyePowder = Item.dyePowder.itemID;
	public static final int bone = Item.bone.itemID;
	public static final int sugar = Item.sugar.itemID;
	public static final int cake = Item.cake.itemID;
	public static final int bed = Item.bed.itemID;
	public static final int redstoneRepeater = Item.redstoneRepeater.itemID;
	public static final int cookie = Item.cookie.itemID;
	public static final int map = Item.map.itemID;
	public static final int shears = Item.shears.itemID;
	public static final int melon = Item.melon.itemID;
	public static final int pumpkinSeeds = Item.pumpkinSeeds.itemID;
	public static final int melonSeeds = Item.melonSeeds.itemID;
	public static final int beefRaw = Item.beefRaw.itemID;
	public static final int beefCooked = Item.beefCooked.itemID;
	public static final int chickenRaw = Item.chickenRaw.itemID;
	public static final int chickenCooked = Item.chickenCooked.itemID;
	public static final int rottenFlesh = Item.rottenFlesh.itemID;
	public static final int enderPearl = Item.enderPearl.itemID;
	public static final int blazeRod = Item.blazeRod.itemID;
	public static final int ghastTear = Item.ghastTear.itemID;
	public static final int goldNugget = Item.goldNugget.itemID;
	public static final int netherStalkSeeds = Item.netherStalkSeeds.itemID;
	public static final int potion = Item.potion.itemID;
	public static final int glassBottle = Item.glassBottle.itemID;
	public static final int spiderEye = Item.spiderEye.itemID;
	public static final int fermentedSpiderEye = Item.fermentedSpiderEye.itemID;
	public static final int blazePowder = Item.blazePowder.itemID;
	public static final int magmaCream = Item.magmaCream.itemID;
	public static final int brewingStand = Item.brewingStand.itemID;
	public static final int cauldron = Item.cauldron.itemID;
	public static final int eyeOfEnder = Item.eyeOfEnder.itemID;
	public static final int speckledMelon = Item.speckledMelon.itemID;
	public static final int monsterPlacer = Item.monsterPlacer.itemID;
	public static final int expBottle = Item.expBottle.itemID;
	public static final int fireballCharge = Item.fireballCharge.itemID;
	public static final int writableBook = Item.writableBook.itemID;
	public static final int writtenBook = Item.writtenBook.itemID;
	public static final int emerald = Item.emerald.itemID;
	public static final int itemFrame = Item.itemFrame.itemID;
	public static final int flowerPot = Item.flowerPot.itemID;
	public static final int carrot = Item.carrot.itemID;
	public static final int potato = Item.potato.itemID;
	public static final int bakedPotato = Item.bakedPotato.itemID;
	public static final int poisonousPotato = Item.poisonousPotato.itemID;
	public static final int emptyMap = Item.emptyMap.itemID;
	public static final int goldenCarrot = Item.goldenCarrot.itemID;
	public static final int skull = Item.skull.itemID;
	public static final int carrotOnAStick = Item.carrotOnAStick.itemID;
	public static final int netherStar = Item.netherStar.itemID;
	public static final int pumpkinPie = Item.pumpkinPie.itemID;
	public static final int firework = Item.firework.itemID;
	public static final int fireworkCharge = Item.fireworkCharge.itemID;
	public static final int enchantedBook = Item.enchantedBook.itemID;
	public static final int comparator = Item.comparator.itemID;
	public static final int netherrackBrick = Item.netherrackBrick.itemID;
	public static final int netherQuartz = Item.netherQuartz.itemID;
	public static final int minecartTnt = Item.minecartTnt.itemID;
	public static final int minecartHopper = Item.minecartHopper.itemID;
	public static final int horseArmorIron = Item.horseArmorIron.itemID;
	public static final int horseArmorGold = Item.horseArmorGold.itemID;
	public static final int horseArmorDiamond = Item.horseArmorDiamond.itemID;
	public static final int leash = Item.leash.itemID;
	public static final int nameTag = Item.nameTag.itemID;
	
	public static final int record13 = Item.record13.itemID;
	public static final int recordCat = Item.recordCat.itemID;
	public static final int recordBlocks = Item.recordBlocks.itemID;
	public static final int recordChirp = Item.recordChirp.itemID;
	public static final int recordFar = Item.recordFar.itemID;
	public static final int recordMall = Item.recordMall.itemID;
	public static final int recordMellohi = Item.recordMellohi.itemID;
	public static final int recordStal = Item.recordStal.itemID;
	public static final int recordStrad = Item.recordStrad.itemID;
	public static final int recordWard = Item.recordWard.itemID;
	public static final int record11 = Item.record11.itemID;
	public static final int recordWait = Item.recordWait.itemID;
}
